# Generated by Django 3.1.1 on 2023-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(unique=True)),
                ('area', models.CharField(max_length=20)),
                ('room_price', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('area__gte', 0), ('room_number__gte', 0), ('room_price__gte', 0)), name='gte 0'),
        ),
    ]
